import{spawnSync}from "node:child_process";
import fs from "node:fs";
const py=cmd=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:"inherit"});if(r.status!==0)process.exit(r.status??1)};
const js=cmd=>py(["node",...cmd]);
js(["scripts/run-production.mjs"]);
js(["scripts/tts_build.mjs"]);
py(["python3","scripts/render_storyboard.py"]);
py(["python3","scripts/selfcheck.py"]);
js(["scripts/materialize-ir.mjs"]);
js(["scripts/build-groups.mjs"]);
console.log("FLOW STOP: pilot preview is ready; run npm run preview then npm run pilot, approve before full render.");
