import fs from "node:fs";
import {spawnSync} from "node:child_process";
const render=spawnSync(process.execPath,["scripts/render-p4.mjs"],{stdio:"inherit"});
if(render.status!==0) process.exit(render.status||1);
const file="artifacts/render/demo.mp4";
if(!fs.existsSync(file)) throw new Error("missing "+file);
const stat=fs.statSync(file);
if(stat.size<10000) throw new Error("rendered MP4 is unexpectedly small");
const probe=spawnSync("ffprobe",["-v","error","-show_entries","format=duration","-of","default=noprint_wrappers=1:nokey=1",file],{encoding:"utf8"});
if(probe.status!==0) throw new Error("ffprobe failed");
const duration=Number(probe.stdout.trim());
if(!(duration>0)) throw new Error("invalid MP4 duration");
console.log(JSON.stringify({stage:"P4",status:"PASS",file,duration_bytes:stat.size,duration_seconds:duration},null,2));
